version: "3.3"

services:
  database:
    image: postgres
    container_name: database_usuarios
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=crud
      - POSTGRES_DB=petrucio
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
